apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: microservice
  template:
    metadata:
      labels:
        app.kubernetes.io/component: microservice
    spec:
      serviceAccountName: sa
      imagePullSecrets:
        - name: pull-secret
      containers:
        - name: application
          image: app-image:latest
          ports:
            - containerPort: 8080
              name: http
          resources:
            limits:
              cpu: 500m
              memory: 3Gi
            requests:
              cpu: 30m
              memory: 500M
          livenessProbe:
            httpGet:
              path: /hc
              port: 8080
            failureThreshold: 3 # When a probe fails, Kubernetes will try failureThreshold times before giving up. Giving up in case of liveness probe means restarting the container. In case of readiness probe the Pod will be marked Unready. Defaults to 3. Minimum value is 1.
            initialDelaySeconds: 5 # Number of seconds after the container has started before liveness or readiness probes are initiated. Defaults to 0 seconds. Minimum value is 0.
            periodSeconds: 60 # How often (in seconds) to perform the probe. Default to 10 seconds. Minimum value is 1.
            timeoutSeconds: 5 # Number of seconds after which the probe times out. Defaults to 1 second. Minimum value is 1.
          readinessProbe:
            httpGet:
              path: /hc
              port: 8080
            failureThreshold: 3 # When a probe fails, Kubernetes will try failureThreshold times before giving up. Giving up in case of liveness probe means restarting the container. In case of readiness probe the Pod will be marked Unready. Defaults to 3. Minimum value is 1.
            initialDelaySeconds: 5 # Number of seconds after the container has started before liveness or readiness probes are initiated. Defaults to 0 seconds. Minimum value is 0.
            periodSeconds: 60 # How often (in seconds) to perform the probe. Default to 10 seconds. Minimum value is 1.
            timeoutSeconds: 5 # Number of seconds after which the probe times out. Defaults to 1 second. Minimum value is 1.